### ISSUE TITLE
its not filling form completely

### ISSUE THREAD

**Issue by aravindravva** [vineetjk/rit-course-reg#1]
can you please resolve this bug form is incomplete
![image](https://user-images.githubusercontent.com/54105449/91628077-012ba000-e9da-11ea-96f9-328d114db7b0.png)

**Comment by vineetjk** [comment]
thanks for raising this issue @aravindravva ..
This bug is fixed.. Kindly try filling your data again.. Don't forget to upload sign otherwise file will not download..

**Comment by aravindravva** [comment]
Yup I checked morning it's fixed and working fine
Thanks for an amazing application

**Comment by vineetjk** [comment]
thank you😇
